---
title: "Acceptance Testing Brussels Sprouts"
type: "challenge"
description: "Writing simple acceptance tests for a Brussels Sprouts Recipe site"
visibility: "assign"
ignore:
- "acceptance-testing-brussel-sprouts.md"
